name: Azure Automation Pipeline

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Login in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'
      - name: Install Dependencies
        run: pip install requirements.txt
      - name: Run python code
        run: python resources.py