name: Azure Automation Pipeline

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
          